version: '2'
services:
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.dev
    volumes:
      - .:/happ
    links:
      - mongo
      - rabbitmq

  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.dev
    links:
      - mongo
      - rabbitmq
