version: '2'
services:
  media:
    extends:
      file: docker-compose.base.yml
      service: media

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - ./conf/nginx/dev:/etc/nginx/sites-enabled
    volumes_from:
      - media
    links:
      - app

  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.test
    links:
      - mongo
      - rabbitmq
    volumes_from:
      - media

  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.test
    links:
      - mongo
      - rabbitmq
