version: '2'
services:
  media:
    extends:
      file: docker-compose.base.yml
      service: media

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - ./conf/dev/nginx/docker:/etc/nginx/sites-enabled
    volumes_from:
      - media
    links:
      - app
    ports:
      - "9000:80"

  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    image: askhatomarov/happ:latest
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.test
    links:
      - mongo
      - rabbitmq
    working_dir: /happ
    volumes:
      - .:/happ
    volumes_from:
      - media
    ports:
      - "8000:8000"

  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    image: askhatomarov/happ:latest
    environment:
      - DJANGO_SETTINGS_MODULE=happ.settings.test
    volumes:
      - .:/happ
    links:
      - mongo
      - rabbitmq
